### ISSUE TITLE
unsused containers are not deleted automatically

### ISSUE THREAD

**Issue by sunnysmol** [backend-developers-ltd/ComputeHorde#43]

**Comment by ppolewicz** [comment]
This is being addressed by https://github.com/backend-developers-ltd/ComputeHorde/pull/59

**Comment by emnoor-reef** [comment]
In earlier versions, some containers with `keep_` prefix were created. You can safely remove them.

From the latest release, containers will be removed after jobs (as was previously), and images will be pruned if configured threshold crosses.

For details, see #59
